// web/src/lib/components/ProjectCard.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let {
		title,
		href,
		buttonText,
		buttonColor = 'bg-primary-600 hover:bg-primary-700',
		children
	}: {
		title: string;
		href?: string;
		buttonText: string;
		buttonColor?: string;
		children: Snippet;
	} = $props();
</script>

<div class="project-card-blur relative w-full md:w-1/2 md:max-w-[348px] xl:w-1/3 xl:max-w-[330px]">
	<div class="relative flex h-full flex-col justify-between p-6">
		<div class="pb-8">
			<h2 class="mb-3 text-2xl font-bold leading-8 tracking-tight">
				{#if href}
					<a href={href} class="hover:underline">{title}</a>
				{:else}
					{title}
				{/if}
			</h2>
			<div class="prose max-w-none text-gray-500 dark:text-gray-400">
				{@render children()}
			</div>
		</div>
		{#if href}
			<a
				href={href}
				class="inline-block rounded px-4 py-2 text-center text-sm font-medium text-white {buttonColor}"
			>
				{buttonText}
			</a>
		{:else}
			<span
				class="inline-block rounded bg-gray-600 px-4 py-2 text-center text-sm font-medium text-white"
			>
				{buttonText}
			</span>
		{/if}
	</div>
</div>

// components/ProjectCard.tsx
import { ReactNode } from 'react'
import Image from './Image'
import Link from './Link'
import ProjectButton from './ProjectButton'

interface Props {
  title: string
  imgSrc?: string
  href?: string
  children?: ReactNode
  buttonText: string
  buttonColor?: string
}

const ProjectCard = ({ title, imgSrc, href, children, buttonText, buttonColor }: Props) => (
  <div className="project-card-blur relative w-full md:w-1/2 md:max-w-[348px] xl:w-1/3 xl:max-w-[330px]">
    <div className="flex h-full flex-col justify-between p-6">
      <div className="pb-8">
        {imgSrc && (
          <Image
            alt={title}
            src={imgSrc}
            className="object-cover object-center md:h-36 lg:h-48"
            width={544}
            height={306}
          />
        )}
        <h2 className="mb-3 text-2xl font-bold leading-8 tracking-tight">
          {href ? (
            <Link href={href} aria-label={`Link to ${title}`}>
              {title}
            </Link>
          ) : (
            title
          )}
        </h2>
        <p className="prose mb-3 max-w-none text-gray-500 dark:text-gray-400">{children}</p>
      </div>
      <ProjectButton as="a" href={href} buttonColor={buttonColor}>
        {buttonText}
      </ProjectButton>
    </div>
  </div>
)

export default ProjectCard
